"""add diff_pendente to projetos_geracao

Revision ID: 049999ce6237
Revises: 25e7d2b6a15b
Create Date: 2026-09-07 04:59:54.558379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '049999ce6237'
down_revision: Union[str, Sequence[str], None] = '25e7d2b6a15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos_geracao', sa.Column('diff_pendente', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos_geracao', 'diff_pendente')
    # ### end Alembic commands ###
