"""add_unique_constraint_consolidacoes_pendentes

Revision ID: 25e7d2b6a15b
Revises: 72b7ec6d2dc4
Create Date: 2026-09-03 22:14:12.081006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e7d2b6a15b'
down_revision: Union[str, Sequence[str], None] = '72b7ec6d2dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_nome_bruto_cliente_sugerido', 'consolidacoes_pendentes', ['nome_bruto_id', 'cliente_sugerido_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_nome_bruto_cliente_sugerido', 'consolidacoes_pendentes', type_='unique')
    # ### end Alembic commands ###
