"""schema inicial - 7 tabelas

Revision ID: 72b7ec6d2dc4
Revises: 
Create Date: 2026-08-30 17:44:28.236892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72b7ec6d2dc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_oficial', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('sucesso', 'erro', 'em_andamento', name='status_etl_run'), nullable=False),
    sa.Column('linhas_processadas', sa.Integer(), nullable=True),
    sa.Column('erros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('papel', sa.Enum('admin', name='papel_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('nomes_brutos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_bruto', sa.Text(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('primeira_ocorrencia', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_ocorrencia', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_ocorrencias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_bruto')
    )
    op.create_table('projetos_geracao',
    sa.Column('ceg', sa.Text(), nullable=False),
    sa.Column('nome_projeto', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('fase', sa.String(), nullable=True),
    sa.Column('potencia_outorgada_kw', sa.Float(), nullable=True),
    sa.Column('inicio_vigencia_ano', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status_revisao', sa.Enum('pendente', 'aprovado', 'rejeitado', name='status_revisao'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('ceg')
    )
    op.create_index(op.f('ix_projetos_geracao_cliente_id'), 'projetos_geracao', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_projetos_geracao_criado_em'), 'projetos_geracao', ['criado_em'], unique=False)
    op.create_index(op.f('ix_projetos_geracao_fase'), 'projetos_geracao', ['fase'], unique=False)
    op.create_index(op.f('ix_projetos_geracao_inicio_vigencia_ano'), 'projetos_geracao', ['inicio_vigencia_ano'], unique=False)
    op.create_index(op.f('ix_projetos_geracao_origem'), 'projetos_geracao', ['origem'], unique=False)
    op.create_index(op.f('ix_projetos_geracao_uf'), 'projetos_geracao', ['uf'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('substituido_por_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['substituido_por_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('consolidacoes_pendentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_bruto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_sugerido_id', sa.UUID(), nullable=False),
    sa.Column('score_similaridade', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='status_consolidacao'), nullable=False),
    sa.Column('decidido_por', sa.UUID(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_sugerido_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['decidido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['nome_bruto_id'], ['nomes_brutos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consolidacao_ceg',
    sa.Column('consolidacao_id', sa.Integer(), nullable=False),
    sa.Column('ceg', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ceg'], ['projetos_geracao.ceg'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consolidacao_id'], ['consolidacoes_pendentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consolidacao_id', 'ceg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consolidacao_ceg')
    op.drop_table('consolidacoes_pendentes')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projetos_geracao_uf'), table_name='projetos_geracao')
    op.drop_index(op.f('ix_projetos_geracao_origem'), table_name='projetos_geracao')
    op.drop_index(op.f('ix_projetos_geracao_inicio_vigencia_ano'), table_name='projetos_geracao')
    op.drop_index(op.f('ix_projetos_geracao_fase'), table_name='projetos_geracao')
    op.drop_index(op.f('ix_projetos_geracao_criado_em'), table_name='projetos_geracao')
    op.drop_index(op.f('ix_projetos_geracao_cliente_id'), table_name='projetos_geracao')
    op.drop_table('projetos_geracao')
    op.drop_table('nomes_brutos')
    op.drop_table('usuarios')
    op.drop_table('etl_runs')
    op.drop_table('clientes')
    # ### end Alembic commands ###
